canary:
  analysis:
    interval: 1m
    maxWeight: 60
    metrics:
      latency:
        interval: 1m
        threshold: 500
    stepWeight: 20
    threshold: 5
  enabled: false
  host: ""
  progressDeadlineSeconds: 60
env: null
hpa:
  cpuTargetAverageUtilization: 80
  enabled: false
  maxReplicas: 6
  memoryTargetAverageUtilization: 80
  minReplicas: 2
image:
  pullPolicy: IfNotPresent
  repository: 274295908850.dkr.ecr.eu-west-1.amazonaws.com/pauwels-labs/redact-feed-api
  tag: 0.0.2
ingress:
  annotations: {}
  classAnnotation: ""
jx:
  imagePullSecrets: []
  releaseCRD: true
jxRequirements:
  ingress:
    annotations: {}
    apiVersion: extensions/v1beta1
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""
knativeDeploy: false
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  probePath: ""
  successThreshold: 1
  timeoutSeconds: 1
probePath: /
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  probePath: ""
  successThreshold: 1
  timeoutSeconds: 1
replicaCount: 1
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
service:
  annotations: {}
  externalPort: 80
  internalPort: 8080
  name: redact-feed-api
  type: ClusterIP
serviceAccount:
  annotations: {}
  enabled: true
  labels: {}
  name: ""
